spring:
  application:
    name: uaa-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wl_auth2?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    serialization:
      indent-output: true
server:
  port: 9999
debug: true




